## torch 본격적으로

In [ ]:
import torch
a=torch.([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=torch.tensor([1,2, 3.1   , 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [ ]:
A=torch.tensor([[1,2,3],[3,4,5]]) # 이 셀부터는 import torch 는 실행 했다 치고 작성
# Atorch=.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [ ]:
print(torch.zeros(5))
print(torch.zeros_like(A)) # A와 같은 shape의 0으로 채워진 텐서
print(torch.ones(5))
print(torch.zeros( 3,3 ))
print(torch.arange(3,10,2)) # range랑 같은데 tensor로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서부터 1 포함(default) 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [ ]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C) 
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## pytorch 의 인덱싱 슬라이스

In [ ]:
a=torch.tensor([1,2,3,4,5,6,7,8,9]) 
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0]) 
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [ ]:
# 3차원 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,   
                 [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape) 
print(A[0,1,2])

a=torch.tensor([[[3,4,5,6]]]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [ ]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A>3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A>3] = 100
print(A) # 그러면 이런 것도 가능하다! (3보다 큰애들을 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([4, 5, 7])
tensor([[  1,   2,   3, 100],
        [100,   3, 100,   3]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [ ]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [ ]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## pytorch의 여러 함수들

In [ ]:
A=torch.randn(3,3) # Normal의 n
B=torch.rand(3,3) # 이건 uniform
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[-1.4740, -0.1145, -0.2977],
        [ 0.7295,  0.1686, -0.0496],
        [ 0.9012, -0.6210, -1.3800]])
tensor([[0.9141, 0.6691, 0.0333],
        [0.3754, 0.6951, 0.4863],
        [0.3543, 0.9568, 0.4791]])
tensor([[-1.4740, -0.1145, -0.2977]])


In [ ]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1   #주의! torch.exp(1) = error!
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 0.9608,  0.8523, -0.6820],
        [ 1.3323,  0.5321, -1.2132],
        [-0.3762, -0.8956, -0.8966]])
tensor([[0.9608, 0.8523, 0.6820],
        [1.3323, 0.5321, 1.2132],
        [0.3762, 0.8956, 0.8966]])
tensor([[0.9802, 0.9232, 0.8258],
        [1.1542, 0.7294, 1.1014],
        [0.6134, 0.9464, 0.9469]])
tensor([[2.6139, 2.3450, 0.5056],
        [3.7896, 1.7025, 0.2973],
        [0.6865, 0.4083, 0.4079]])
tensor([[-0.0399, -0.1599, -0.3827],
        [ 0.2869, -0.6310,  0.1932],
        [-0.9776, -0.1102, -0.1091]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[ 1.,  1., -1.],
        [ 1.,  1., -1.],
        [-0., -1., -1.]])
tensor([[ 0.9600,  0.8500, -0.6800],
        [ 1.3300,  0.5300, -1.2100],
        [-0.3800, -0.9000, -0.9000]])
tensor([[ 0.,  0., -1.],
        [ 1.,  0., -2.],
        [-1., -1., -1.]])
tensor([[ 1.,  1., -0.],
        [ 2.,  1., -1.],
        [-0., -0., -0.]])


In [ ]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- 토치 파이는 float이지만, 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [9]:
import torch

type(torch.pi)
torch.log(torch.tensor(1))

tensor(0.)

In [ ]:
torch.nan # not a number
torch.log(torch.tensor(-1))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
A=torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0))
print(torch.max(A,dim=1)) # 1D array로 바꿔버림
print(torch.max(A,dim=0, keepdims=True))
print(torch.max(A,dim=1, keepdims=True)) # 3 행 1열 짜리 2D tensor
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A))
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[ 1.5816, -0.9170, -1.8009,  1.7364],
        [ 1.0022, -0.1015, -0.2307,  1.9819],
        [ 0.6689,  1.4289, -0.8728,  0.4382]])
tensor(1.9819)
torch.return_types.max(
values=tensor([ 1.5816,  1.4289, -0.2307,  1.9819]),
indices=tensor([0, 2, 1, 1]))
torch.return_types.max(
values=tensor([1.7364, 1.9819, 1.4289]),
indices=tensor([3, 3, 1]))
torch.return_types.max(
values=tensor([[ 1.5816,  1.4289, -0.2307,  1.9819]]),
indices=tensor([[0, 2, 1, 1]]))
torch.return_types.max(
values=tensor([[1.7364],
        [1.9819],
        [1.4289]]),
indices=tensor([[3],
        [3],
        [1]]))
tensor(-1.8009)
torch.return_types.min(
values=tensor([ 0.6689, -0.9170, -1.8009,  0.4382]),
indices=tensor([2, 0, 0, 2]))
torch.return_types.min(
values=tensor([-1.8009, -0.2307, -0.8728]),
indices=tensor([2, 2, 2]))
tensor(7)
tensor([0, 2, 1, 1])
tensor([3, 3, 1])


In [ ]:
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0)
print(a_sorted)

a=torch.randn(6,1)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor([[-0.9172],
        [-0.3115],
        [ 1.2793],
        [-0.3870],
        [-0.2347],
        [ 0.3376]])
torch.return_types.sort(
values=tensor([[-0.9172],
        [-0.3870],
        [-0.3115],
        [-0.2347],
        [ 0.3376],
        [ 1.2793]]),
indices=tensor([[0],
        [3],
        [1],
        [4],
        [5],
        [2]]))
torch.return_types.sort(
values=tensor([[-2.7196],
        [-0.5565],
        [-0.4622],
        [-0.4303],
        [-0.3988],
        [-0.1039]]),
indices=tensor([[4],
        [5],
        [2],
        [3],
        [0],
        [1]]))
torch.return_types.sort(
values=tensor([[-0.1039],
        [-0.3988],
        [-0.4303],
        [-0.4622],
        [-0.5565],
        [-2.7196]]),
indices=tensor([[1],
        [0],
        [3],
        [2],
        [5],
        [4]]))
tensor(-0.1039)
tensor(-0.1039)
tensor([[0.3988],
        [0.1039],
        [0.4622],
        [0.4303],
        [2.7196],
        [0.5565]])
tensor([[0.3988],
        [0.1039],


In [ ]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[-1.6230e+00,  1.2844e+00,  1.1063e+00,  3.7231e-01],
        [-4.0481e-01,  6.5913e-01,  8.8628e-04, -9.0618e-01],
        [ 2.0323e-01,  1.3782e+00,  2.1957e+00,  9.1018e-01]])
tensor(5.1764)
tensor([ 1.1400, -0.6510,  4.6873])
tensor([[ 1.1400],
        [-0.6510],
        [ 4.6873]])
tensor(0.4314)
tensor([ 0.2850, -0.1627,  1.1718])
tensor([[ 0.2850],
        [-0.1627],
        [ 1.1718]])
tensor(1.0627)
tensor([[ 1.1400],
        [-0.6510],
        [ 4.6873]])
tensor([[ 0.2850],
        [-0.1627],
        [ 1.1718]])
tensor(1.0627)


In [ ]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

tensor([1, 3, 4, 4, 3, 2, 2, 2, 3, 4, 3, 2])
torch.Size([12])
tensor([[[1, 3, 4],
         [4, 3, 2]],

        [[2, 2, 3],
         [4, 3, 2]]])
3


In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b) # permute가 더 좋다 왜 ? transpose는 2차원 행렬만 가능하지만, permute는 2차원 이상의 행렬도 가능하다
print(a.T@b)
print(a.t()@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape) # 4,6,3

# 참고
# transpose 의 경우에는 그냥 순서 상관없이 두개만 바꿔주면 된다
# permute 의 경우에는 순서를 바꿔주는 것이다
# 예를 들어
# A=torch.randn(4,3,6)
# print(A.permute(0,2,1).shape) # 4,6,3
# print(A.permute(0,1,2).shape) # 4,3,6
# print(A.permute(2,1,0).shape) # 6,3,4
# print(A.permute(2,0,1).shape) # 6,4,3
# print(A.permute(1,0,2).shape) # 3,4,6
# transpose 의 경우에는
# print(A.transpose(0,1).shape) # 3,4,6
# print(A.transpose(0,2).shape) # 6,3,4
# print(A.transpose(1,2).shape) # 4,6,3
# print(A.transpose(1,0).shape) # 3,4,6


tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])


In [ ]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [ ]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape) 
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [ ]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
C=torch.vstack([A,B]) 
D=torch.hstack([A,B]) # v는 0번째 차원, h는 1번째 차원에 쌓는다. (A,B 사이즈 (2,3,4)로 추가 해보기) 가급적 3차 이상의 텐서에는 사용하지 않는 것이 좋다
E=torch.cat([A,B], dim=0)
F=torch.cat([A,B], dim=1)
# G=torch.cat([A,B], dim=2)

print(C)
print(D)
print(E)
print(F)
# print(G)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [11]:
A = torch.randn(1,1,1,3,1,1,4,1)
print(A)
print(A.shape)
print(A.squeeze().shape)

tensor([[[[[[[[ 0.2950],
              [-0.7118],
              [ 0.2723],
              [-0.0418]]]],



           [[[[ 0.0845],
              [-0.4334],
              [ 0.3632],
              [ 1.0408]]]],



           [[[[-0.5292],
              [ 1.9320],
              [ 1.3440],
              [-0.7689]]]]]]]])
torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [ ]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [ ]:
# 사용법 : 채널 쪽으로 차원을 추가하고 싶을 때 아래의 코드를 사용하면 된다
A=torch.ones(3,4)
B=torch.zeros(3,4)
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0]=100

print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @ 에 대해 좀만 더

In [ ]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [ ]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1)
D=A@B

print(C.shape)
print(D.shape)
print((C-D).abs().max())

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(9.5367e-07)


In [ ]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A)
print(A_repeat)
print(A_repeat.shape)

tensor([[0.4890, 0.1937, 0.3766],
        [0.7003, 0.3296, 0.5333]])
tensor([[[[0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333],
          [0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333],
          [0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333]]],


        [[[0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333],
          [0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333],
          [0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333]]],


        [[[0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.3296, 0.5333, 0.7003, 0.3296, 0.5333],
          [0.4890, 0.1937, 0.3766, 0.4890, 0.1937, 0.3766],
          [0.7003, 0.32

## numpy <-> torch 왔다갔다 가능

In [ ]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])
A=torch.tensor(a) # A=torch.from_numpy(a)
B=b.numpy() # B=np.array(b)
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


## 딥러닝을 가능케한 autograd

In [ ]:
x = torch.tensor([1.], requires_grad=True) # float 이여야해서 1.
print(x)

# 나 x로 미분할 준비 하겠다!

tensor([1.], requires_grad=True)


In [ ]:
x = torch.tensor([1.])
print(x)
print(x.requires_grad)

x.requires_grad=True
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y) # PowBackward0 가 붙어있다!

print(x.grad)
y.backward()
print(x.grad) # y=x**2을 미분한 2x의 x 값에 1을 대입한 gradient 값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y)
y.retain_grad() # 이걸 하면 y.grad도 볼 수 있다

z = 3*y
print(z) # MulBackward0 가 붙어있다

z.backward()
print(x.grad) # chain rule로 알아냄
# print(y.grad) # warning! 중간건 안된다

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
z = 3*y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감 (backward!)
print(x.grad)

tensor([2.])


In [ ]:
x = torch.tensor([1.], requires_grad=True)
a = x**2
b = a+1
print(b) # AddBackward0 가 붙어있다.
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= y*x**2
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([1.])


In [ ]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [ ]:
x=torch.tensor([1.] ,requires_grad=True)
x.requires_grad=False 
# tranfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


In [ ]:
x=torch.tensor([2.] ,requires_grad=True)
x=x.detach() # detach도 많이 쓰이는 듯
print(x)
y=x**2
print(y)

tensor([2.])
tensor([4.])


In [ ]:
# detach 와 torch.no_grad
x=torch.tensor([1.], requires_grad=True)
# chain rule을 위해 계속 grad_fn을 update 하니까 grad_fn 잠시 안 계산하고 싶을 때 torch.no_grad
# 모델 테스트 시에는 불필요하게 메모리 쓸 필요 없기 때문!
with torch.no_grad(): 
    y = x**2
    print(x.requires_grad)
    print(y) # with 안에서 계산되는 애는 grad_fn 이 안붙음
    # 즉 연산 자체는 하되 grad_fn라는 attribute가 안 붙음
print(x.requires_grad)
# y.backward() # error! # 즉 여기선 에러가 당연히 뜨겠지. with 안에서 계산된 애들은 grad_fn이 안 붙었으니까
y=x**2
print(y)

x=torch.tensor([1.], requires_grad=True)
x=x.detach() # detach는 계산은 하되 grad_fn이 붙지 않음. 즉 torch.no_grad 와 비슷
y = x**2
print(x.requires_grad)
print(y)
# y.backward() # error!

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)
False
tensor([1.])


In [12]:
# !pip install torchviz
from torchviz import make_dot
x=torch.tensor([1.],requires_grad=True)
# make_dot(x)
# make_dot(x**2)
# make_dot(x**2+1)
make_dot((x**2+1)**2)

ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

## 간단한 인공신경망 만들기

In [5]:
import torch
from torch import nn

x = torch.tensor([1.])
model = nn.Linear(1,1) # 입력 node 한 개, 출력 node 한 개인 layer 만듦
# 채널, 피쳐, 노드 수 다 같은말임!s
print(model)

print(model.weight) # 만들면서 initialize 함
print(model.bias)

y=model(x)
print(y)

y = x @ model.weight + model.bias
print(y)

Linear(in_features=1, out_features=1, bias=True)
Parameter containing:
tensor([[0.0104]], requires_grad=True)
Parameter containing:
tensor([-0.7301], requires_grad=True)
tensor([-0.7197], grad_fn=<AddBackward0>)
tensor([-0.7197], grad_fn=<AddBackward0>)


In [ ]:
fc1=nn.Linear(1,3) # fully-connected , 1개가 인풋이고 3개가 아웃풋임.
fc2=nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x = torch.tensor([1.])
x = fc1(x)
print(x)
x = fc2(x)
print(x)

x = torch.tensor([1.])
y = (x @ fc1.weight.T + fc1.bias) @ fc2.weight.T + fc2.bias
# nn.Linear 는 개x채x행x열에서 "채" 형태로 (1D data) 들어오길 기대하는 녀석이다 (채널, 피쳐, 노드 수 다 같은말임!)
# 즉, 노드 하나가 곧 한 채널의 의미한다.                  
# 따라서, 데이터 여러개를 통과시키고 싶다면 개x채 의 형태로 줘야 함

# 다른 예시
# 3x5 행렬은 개수가 3개, 채널이 5개인 행렬이다. 
    # 그냥 채널이 5개인 데이터를 3개 가지고 있다는 뜻이다.
    # 즉 nn.Linear(5,?) 가 되어야만 한다
# 3x5 행렬을 nn.Linear(5,10)에 넣으면 3x10 행렬이 나온다.
# 다시, Linear(a,b)는 a개의 채널을 가진 데이터를 b개의 채널로 바꾼다는 뜻이다. 

# why T? 왜 weight를 transpose 해주지?
    # weight 도 개x채 형태로 만들기 위함!!
    # 아 input data랑 형태를 맞춰주기 위함!
# 일단, weight shape 개x채에서 채는 무조건 앞에 거 채널 개수와 맞추셈!
# 예를 들어, nn.Linear(2,3)이면 앞에 거 채널 개수는 2 따라서 ?x2 인데
# 두 채널 값을 가지고 3개의 노드를 만드는 거라서 3x2 가 된다!


print(y)
# input size: 1
# fc1.weight.T size: 1x3
# fc1.bias size: 3
# fc2.weight.T size: 3x1
# fc2.bias size: 1

Parameter containing:
tensor([[ 0.5796],
        [ 0.3320],
        [-0.7347]], requires_grad=True)
Parameter containing:
tensor([0.6033, 0.7442, 0.7983], requires_grad=True)
Parameter containing:
tensor([[ 0.5391, -0.0322, -0.4377]], requires_grad=True)
Parameter containing:
tensor([0.1691], requires_grad=True)
tensor([1.1830, 1.0762, 0.0636], grad_fn=<AddBackward0>)
tensor([0.7444], grad_fn=<AddBackward0>)
tensor([0.7444], grad_fn=<AddBackward0>)


In [8]:
# 더이상 헷갈리지 말자!
# nn.Linear(1,3)은 1개의 채널을 가진 데이터를 3개의 채널로 바꾼다는 뜻이다.
x = torch.tensor([[1.],[2.],[3.]]) # 3x1 = 채널이 1개인 데이터 3개
x = torch.tensor([[1.,2.,3.]]) # 1x3 = 채널이 3개인 데이터 1개
x = torch.tensor([1.,2.,3.]) # 3 = 채널이 3개인 데이터 1개

In [ ]:
fc1=nn.Linear(1,3)
fc2=nn.Linear(3,1)

x = torch.tensor([1.])
x = fc1(x)
print(x)
x = fc2(x)
print(x)

model = nn.Sequential(fc1, fc2) # layer 풀칠
x = torch.tensor([1.])
print(model(x))

tensor([ 0.9580, -0.5387, -0.5935], grad_fn=<AddBackward0>)
tensor([0.7850], grad_fn=<AddBackward0>)
tensor([0.7850], grad_fn=<AddBackward0>)


In [ ]:
model = nn.Sequential(nn.Linear(2,5), # 여기는 채, 채
                      nn.Linear(5,10),
                      nn.Linear(10,3))

x=torch.randn(2)
print(x)
print(model(x))

x=torch.randn(1,2)
print(x)
print(model(x))

x=torch.randn(5,2) # 개x채 => 두 개의 채널 값(키, 몸무게)을 가지는 데이터(사람) 5개를 통과시킴
print(x)
print(model(x))

x=torch.randn(2,3,1,4,5,2) # 얘가 왜 되는지?
print(model(x).shape)

tensor([ 0.5511, -0.7286])
tensor([ 0.0594,  0.2636, -0.3639], grad_fn=<AddBackward0>)
tensor([[-0.3146,  0.0865]])
tensor([[-0.1931,  0.1771, -0.1086]], grad_fn=<AddmmBackward0>)
tensor([[ 1.3381,  0.0861],
        [-1.5835, -1.0218],
        [-1.2782,  2.2704],
        [ 1.1006, -0.3900],
        [-1.0521,  0.4714]])
tensor([[ 0.3853,  0.1420, -0.4002],
        [-0.7059,  0.3468, -0.0244],
        [-0.3950, -0.0835,  0.3364],
        [ 0.2727,  0.2083, -0.4182],
        [-0.4274,  0.1432,  0.0700]], grad_fn=<AddmmBackward0>)
torch.Size([2, 3, 1, 4, 5, 3])


In [ ]:
class MyModel(nn.Module):
    def __init__(self):  
        super().__init__() # nn.Module의 init을 불러옴
    # 어떤 layer를 쓸지 정의
        self.fc1 = nn.Linear(2,5)
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()

    # 어떻게 layer를 통과시킬지 정의
    def forward(self, x):
        x = self.fc1(x)
        x = self.sig1(x)
        x = self.fc2(x)
        x = self.sig2(x)
        x = self.fc3(x)
        x = self.sig3(x)
        return x

model = MyModel()
x = torch.randn(5,2) # 5개의 데이터, 2개의 채널(피쳐, 노드)
y = model(x) # forward 함수가 실행됨, 즉 model.forward(x)가 실행됨
print(y)

tensor([[0.5218, 0.4194, 0.3549],
        [0.5205, 0.4182, 0.3569],
        [0.5227, 0.4203, 0.3538],
        [0.5232, 0.4202, 0.3573],
        [0.5234, 0.4210, 0.3544]], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model)
print(model.fc1.weight)
print(model.fc2.bias)

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)
Parameter containing:
tensor([[-0.1662, -0.5805],
        [-0.5876,  0.4499],
        [ 0.3691, -0.3692],
        [-0.0203, -0.2419],
        [-0.1587,  0.2660]], requires_grad=True)
Parameter containing:
tensor([ 0.2232,  0.2224, -0.0344,  0.0513,  0.2333, -0.1718,  0.2732, -0.2634,
         0.2561,  0.1983], requires_grad=True)


In [9]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear = nn.Sequential(nn.Linear(2,5),
                                    nn.Sigmoid(),
                                    nn.Linear(5,10),
                                    nn.Sigmoid(),
                                    nn.Linear(10,3),
                                    nn.Sigmoid())

    def forward(self, x):
        x = self.linear(x)
        return x

model2 = MyModel2()
x = torch.randn(5,2)
y = model2(x)
print(y)

tensor([[0.6307, 0.4130, 0.5773],
        [0.6306, 0.4143, 0.5746],
        [0.6323, 0.4161, 0.5729],
        [0.6320, 0.4145, 0.5760],
        [0.6362, 0.4176, 0.5742]], grad_fn=<SigmoidBackward0>)


In [10]:
# Sequential 쓸때와 안쓸때는 뭐가 다른가?

print(model2)
print(model2.linear[0].weight)
print(model2.linear[-2].bias)

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Parameter containing:
tensor([[-0.6994,  0.0343],
        [ 0.2865, -0.1813],
        [-0.1061, -0.6090],
        [-0.0722,  0.4113],
        [-0.0292, -0.5662]], requires_grad=True)
Parameter containing:
tensor([ 0.2928, -0.1753,  0.2498], requires_grad=True)


In [ ]:
list(model.parameters())[2]

Parameter containing:
tensor([[ 0.0669, -0.0478,  0.0582,  0.0538,  0.2860],
        [ 0.2621, -0.2179, -0.3110, -0.0766,  0.1181],
        [-0.0839, -0.1444,  0.4449, -0.3039, -0.0053],
        [ 0.0075,  0.1255, -0.3866,  0.1172, -0.1234],
        [-0.4317,  0.1978, -0.4307,  0.3425, -0.3454],
        [-0.1497,  0.3999,  0.2230,  0.0851,  0.3291],
        [-0.1460, -0.4230,  0.0039, -0.0530, -0.1694],
        [-0.3315,  0.3047, -0.0563,  0.3222,  0.2541],
        [ 0.3212, -0.3409,  0.3902, -0.4376,  0.1413],
        [-0.2126, -0.1242,  0.0035, -0.2435, -0.0093]], requires_grad=True)

In [ ]:
# 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(num)

108


## weight initialization

In [ ]:
# 내 필기용 : He initialization 이 공식 문서랑 다르다? => paper에 맞게 구현됐고 torch 공식 문서만 틀림
import torch
from torch import nn
Fin=5000
Fout=1000
w = torch.zeros(141, Fin)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu') # forward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fin)))
w = torch.zeros(Fout, 212)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu') # backward pass에서 값의 범위를 유지시켜주기 위함
print(w.std())
print(torch.sqrt(torch.tensor(2/Fout)))

# CNN?
N=32
C=64
H=6
W=10
w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(C*H*W))))

w = torch.zeros(N,C,H,W)
nn.init.kaiming_uniform_(w, mode='fan_out', nonlinearity='relu')
print(w.std())
print(torch.sqrt(torch.tensor(2/(N*H*W))))